BIN = userlogin wc pascal-toy

include ../../build.mk

userlogin.c: userlogin.l
userlogin.o: userlogin.c
userlogin: userlogin.o

wc.c: wc.l
wc.o: wc.c
wc: wc.o

pascal-toy.c: pascal-toy.l
pascal-toy.o: pascal-toy.c
pascal-toy: pascal-toy.o
